mun-lang/mun

- crates/mun_runtime/src/lib.rs
A better fix would be to fix the tests but this takes a lot more work and currently the travis build fails. We'll have to revisit this later.
> fix: disables runtime tests on all platform but windows

- ci/azure-coverage.yml
This PR replaces kcov as a test coverage tool with [tarpaulin](https://github.com/xd009642/tarpaulin). 
The downsides of Tarpaulin over kcov are:
* It only works on Linux
* Its a lot less mature
Upsides are:
* It "understands" rust much better which reduces the number of false positives
* Its actively developed
> feat: replace kcov test coverage with tarpaulin

- crates/mun/src/main.rs
> Remove deprecated std::error::Error::description() call

- README.md
The old readme was still from when this repo was the mun runtime
experiment. This readme contains information about Mun, examples,
features, links to the docs and how to build it on different platforms.
> docs(readme): update readme to reflect this repo

- crates/mun_compiler/src/lib.rs
This assumes that the provided file is in the root directory.
> fix(compiler): allow absolute file paths

- crates/mun_runtime_capi/src/lib.rs
Fixes `cargo clippy` failure in the latest `rustc`.
> fix(runtime_capi): resolve cargo errors

- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/test__true_is_true.snap
- crates/mun_codegen/src/test.rs
- crates/mun_hir/src/expr.rs
- crates/mun_runtime/src/test.rs
This PR fixes an issue with boolean literals in the conversion from ast to HIR. I've also added two tests to test the functionality.
> fix: fix boolean literal conversion

- .github/workflows/ci.yml
This replaces upload of test coverage to coveralls with upload to codecov.io. This was previously not possible because of the use of docker containers in the codecov.io upload action. This has recently been replaced so it should work now.
> refactor: use codecov.io instead of coveralls

- crates/mun/src/main.rs
- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/mock.rs
- crates/mun_codegen/src/test.rs
- crates/mun_compiler/src/db.rs
- crates/mun_compiler/src/diagnostics.rs
- crates/mun_compiler/src/diagnostics/emit.rs
- crates/mun_compiler/src/driver.rs
- crates/mun_compiler/src/driver/config.rs
- crates/mun_compiler/src/lib.rs
- crates/mun_compiler_daemon/src/lib.rs
- crates/mun_errors/src/lib.rs
- crates/mun_hir/src/code_model.rs
- crates/mun_hir/src/db.rs
- crates/mun_hir/src/diagnostics.rs
- crates/mun_hir/src/input.rs
- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/mock.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/src/test.rs
- crates/mun_target/Cargo.toml
- crates/mun_target/src/spec.rs
This commit restructures the compiler crates to better support incremental compilation. The compiler `--watch` mode is now incremental, reusing the state from previous compilations.
**Todo:**
> Incremental compilation & hotreloading tests

- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/test__fibonacci_loop.snap
- crates/mun_codegen/src/snapshots/test__loop_expr.snap
- crates/mun_codegen/src/test.rs
- crates/mun_hir/src/expr.rs
- crates/mun_hir/src/ty/infer.rs
- crates/mun_hir/src/ty/snapshots/tests__infer_loop.snap
- crates/mun_hir/src/ty/tests.rs
- crates/mun_runtime/src/test.rs
- crates/mun_syntax/src/ast/generated.rs
- crates/mun_syntax/src/ast/traits.rs
- crates/mun_syntax/src/grammar.ron
- crates/mun_syntax/src/parsing/grammar/expressions.rs
- crates/mun_syntax/src/syntax_kind/generated.rs
- crates/mun_syntax/src/tests/lexer.rs
- crates/mun_syntax/src/tests/parser.rs
- crates/mun_syntax/src/tests/snapshots/lexer__keywords.snap
- crates/mun_syntax/src/tests/snapshots/parser__loop_expr.snap
Enabling a much faster fibonacci:
```mun
fn fibonacci(n:int):int {
let a = 0;
let b = 1;
let i = 1;
loop {
if i > n {
return a
}
let sum = a + b;
a = b;
b = sum;
i += 1;
}
}
```
**Depends on #49**
> Adds `loop` expression

- .github/workflows/ci.yml
- crates/mun_hir/src/ty/infer.rs
This PR fixes a clippy warning for rust 1.40
> fix: clippy warning for rust 1.40

- crates/mun_hir/src/expr.rs
- crates/mun_hir/src/ty/infer.rs
- crates/mun_hir/src/ty/op.rs
- crates/mun_hir/src/ty/snapshots/tests__invalid_binary_ops.snap
- crates/mun_hir/src/ty/tests.rs
This PR basically adds checks to determine whether a binary operation is valid. This test should report an error:
```mun
fn foo() {
let b = false;
let n = 1;
let _ = b + n; // error: invalid binary operation
}
```
> feat: add simple binary operation type checking

- crates/mun_runtime/src/test.rs
> test: add test to check if compiler output strings is valid utf8

- crates/mun_abi/src/autogen_impl.rs
> refactor: replace CStr::from_ptr(ptr).to_str() with from_utf8_unchecked

- crates/mun_compiler/src/driver.rs
- crates/mun_target/src/spec.rs
- crates/mun_target/src/spec/apple_base.rs
- crates/mun_target/src/spec/windows_msvc_base.rs
> feat: compiled libraries have `munlib` extension instead of `dll`/`so`

- crates/mun_abi/src/autogen_impl.rs
Adds `impl fmt::Display` in the ABI autogen to get more correct descriptive error messages
> feat: better error message printing when signature is missing

- crates/mun_codegen/src/ir/adt.rs
- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/test__field_crash.snap
- crates/mun_codegen/src/snapshots/test__struct_test.snap
- crates/mun_codegen/src/test.rs
- crates/mun_runtime/src/test.rs
Fixes an issue when initializing structs with non constant values resulted in a crash.
> fix: struct initialization fix for non constants

- crates/mun_abi/src/autogen_impl.rs
- crates/mun_runtime/src/macros.rs
- crates/mun_runtime/src/reflection.rs
- crates/mun_runtime/src/struct.rs
- crates/mun_runtime/src/test.rs
Depends on PR #84.
Allows getting, setting and replacing of structs in another struct:
```mun
let foo: Struct = some_foo_constructor();
let bar = foo.get<Struct>("bar");
let bar2 = some_bar_constructor();
let old_bar = foo.replace("bar", bar2);
foo.set("bar", old_bar);
```
> Adds structs as a marshallable type

- crates/mun_runtime_capi/Cargo.toml
- crates/mun_runtime_capi/src/lib.rs
- crates/mun_runtime_capi/src/tests.rs
> Add function to runtime CAPI for retrieving StructInfo from a TypeInfo pointer

- crates/mun_codegen/src/ir/ty.rs
- crates/mun_runtime/src/test.rs
> Fix bug caused by erroneous caching of struct types

- .github/workflows/ci.yml
Tokenless uploads has been implemented in https://github.com/codecov/codecov-action/issues/29
We should regenerate the codecov token when this is merged because the old token is still stored in history.
> fix: removed the codecov token

- .github/workflows/ci.yml
So from my point of view these are the pros and cons of using [tarpaulin](https://github.com/xd009642/tarpaulin) over grcov:
**Pros**
* Seems to give more precise coverage
* Better integration in the rust ecosystem
* Actively developed.
**Cons**
* Still has false positives
* Only runs on Ubuntu (so no coverage on macOS and Windows specific paths)
* Might still be unstable because it was in the past
> Replace grcov with tarpaulin for test coverage

- crates/mun_hir/Cargo.toml
- crates/mun_hir/src/mock.rs
- crates/mun_runtime/Cargo.toml
- crates/mun_runtime_capi/Cargo.toml
This improvement reduces the number of dependencies, by using the same `parking_lot` minor version across the board.
> improvement: bump parking_lot dependency to 0.10

- crates/mun_codegen/Cargo.toml
- crates/mun_codegen/src/mock.rs
- crates/mun_codegen/src/test.rs
For now this is limited to a split between `group_ir` and `file_ir` as a _group_ currently exists of a single file. In the future we will need to test that changing one file doesn't cause regeneration of another file.
NOTE: Once we add support for multiple files, we need to do a second optimization round. `file_ir` depends on `group_ir` for usage of the `DispatchTable`, but this could potentially be optimised by adding an `external` LLVM function that MUST be inlined. If we succeed in this optimization, `file_ir` never has to be regenerated when another file's changes cause the `group_ir` to be updated.
> test(code_gen): add incremental compilation test

- crates/mun_hir/src/expr.rs
- crates/mun_hir/src/ty/infer.rs
- crates/mun_hir/src/ty/snapshots/tests__infer_invalid_struct_type.snap
- crates/mun_hir/src/ty/tests.rs
- crates/mun_syntax/src/ast/generated.rs
- crates/mun_syntax/src/grammar.ron
- crates/mun_syntax/src/parsing/grammar/expressions.rs
- crates/mun_syntax/src/tests/snapshots/parser__struct_lit.snap
Fixes an issue whereby using a struct in a record literal that was not defined crashed the compiler. E.g:
```
fn main(){
let a = Foo {b: 3};
}
```
> fix: infer invalid struct type

- crates/mun_codegen/src/ir/type_table.rs
- crates/mun_codegen/src/snapshots/test__extern_fn_file_ir.snap
- crates/mun_codegen/src/snapshots/test__extern_fn_group_ir.snap
Fixes an issue that caused a crash when only `extern` functions were made public. This causes the types of the arguments and return types to not be included in the type table but they should have been.
This touched a test that was actually incorrect before.
> fix: fixes #113

- crates/tools/Cargo.toml
This updates the cbindgen crate from a custom version to the official crate. The changes from our custom version were merged in the official repo: https://github.com/eqrion/cbindgen/pull/446
> misc: updates to official cbindgen crate

- README.md
Thanks to @jakbyte, one of our dependencies - `lld7` - can now be installed using packages. The install instructions were updated accordingly.
> docs(readme): new Arch Linux install instructions

- crates/mun_abi/src/autogen.rs
- crates/mun_abi/src/autogen_impl.rs
- crates/mun_codegen/src/ir/abi_types.rs
- crates/mun_codegen/src/ir/type_table.rs
- crates/mun_codegen/src/snapshots/test__field_crash_group_ir.snap
- crates/mun_codegen/src/snapshots/test__field_expr_group_ir.snap
- crates/mun_codegen/src/snapshots/test__gc_struct_group_ir.snap
- crates/mun_codegen/src/snapshots/test__struct_test_group_ir.snap
- crates/mun_runtime/src/garbage_collector.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/src/macros.rs
- crates/mun_runtime/src/marshal.rs
- crates/mun_runtime/src/reflection.rs
- crates/mun_runtime/src/struct.rs
- crates/mun_runtime/src/test.rs
Instead we collect the most recent `TypeInfo` pointer from the `Runtime`'s
`GcRuntime`. This allows us to maintain the `StructRef` even after hot
reloads.
> refactor: remove TypeInfo and StructInfo from StructRef

- crates/mun_codegen/src/ir.rs
- crates/mun_codegen/src/ir/ty.rs
- crates/mun_codegen/src/snapshots/test__primitive_types_file_ir.snap
- crates/mun_codegen/src/test.rs
- crates/mun_codegen/src/type_info.rs
- crates/mun_hir/src/builtin_type.rs
- crates/mun_hir/src/name.rs
- crates/mun_hir/src/ty/primitives.rs
- crates/mun_hir/src/ty/snapshots/tests__primitives.snap
- crates/mun_hir/src/ty/tests.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/src/macros.rs
- crates/mun_runtime/src/reflection.rs
- crates/mun_runtime/src/test.rs
Also includes `Runtime::invoke_fn15` and a corresponding extra branch to `invoke_fn!`.
> 128-bit integers i128 and u128

- crates/mun_runtime/src/function.rs
- crates/mun_runtime/src/test.rs
This PR fixes an issue where it was not possible to add an extern function like this:
```rust
extern "C" fn foo(a: i64) {
println!("{}", a);
}
```
because it doesn't have a return type and `HasStaticTypeInfo` is not implemented for `()`. 
The PR fixes this by adding an implementation of `IntoFunctionInfo` for functions without a return type.
> feat: add support for extern functions without a return type

- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/test__issue_128_file_ir.snap
- crates/mun_codegen/src/snapshots/test__issue_128_group_ir.snap
- crates/mun_codegen/src/test.rs
There was a bug where functions that returned nothing where seen as
functions that returned `never` during code generation. This caused dead
code elimination to remove the rest of the code.
I solved this issue by making sure that all functions do return
something. Unless the actually return type is `never`.
> fix: fixes #128

- crates/mun_runtime/src/lib.rs
Oops, I guess I left out a space in my last PR.
> style: add a missing space to invoke_fn15's definition

- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/test__unary_expressions.snap
- crates/mun_codegen/src/test.rs
- crates/mun_hir/src/diagnostics.rs
- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/ty/infer.rs
- crates/mun_hir/src/ty/snapshots/tests__infer_unary_ops.snap
- crates/mun_hir/src/ty/snapshots/tests__invalid_unary_ops.snap
- crates/mun_hir/src/ty/tests.rs
I think I've gotten codegen done, but it seems that the type of expressions with unary operators is, for whatever reason, unknown.
> feat: unary operators

- crates/mun_compiler/src/driver/display_color.rs
Colors on my linux terminal did not work because the environment variable that was used to check support was written lowercase. 
I also added support for the `NO_COLOR ` environment variable. https://no-color.org/
> fix: color output on linux terminal

- crates/mun_runtime/src/assembly.rs
- crates/mun_runtime/src/reflection.rs
- crates/mun_runtime/tests/runtime.rs
- crates/mun_runtime/tests/util.rs
Previously, we weren't checking whether the dependencies of the `Assembly` we were trying to link were resolvable.
> fix(runtime): ensure loaded Assemblies can be linked

- crates/mun_memory/src/gc/mark_sweep.rs
- crates/mun_memory/src/lib.rs
- crates/mun_memory/src/mapping.rs
- crates/mun_runtime/src/assembly.rs
- crates/mun_runtime/src/garbage_collector.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/src/reflection.rs
- crates/mun_runtime/src/struct.rs
> cleanup runtime/memory code

- crates/mun_runtime/src/struct.rs
- crates/mun_runtime/tests/marshalling.rs
> feat(runtime): add cloning of StructRef

- crates/mun_hir/src/ty/op.rs
- crates/mun_hir/src/ty/snapshots/tests__comparison_not_implemented_for_struct.snap
- crates/mun_hir/src/ty/tests.rs
The comparison operator is not implemented for structs. This should be reflected in HIR.
> fix: comparison not implemented for structs

- crates/mun_compiler/src/snapshots/mun_compiler__diagnostics__tests__mismatched_type_error.snap
- crates/mun_hir/Cargo.toml
- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/ty.rs
- crates/mun_hir/src/ty/infer.rs
- crates/mun_hir/src/ty/infer/coerce.rs
- crates/mun_hir/src/ty/infer/type_variable.rs
- crates/mun_hir/src/ty/infer/unify.rs
- crates/mun_hir/src/ty/op.rs
- crates/mun_hir/src/ty/snapshots/tests__infer_literals.snap
- crates/mun_hir/src/ty/snapshots/tests__invalid_unary_ops.snap
- crates/mun_hir/src/ty/tests.rs
- crates/mun_hir/src/utils.rs
Implements type inferencing of number types.
Closes #118
> feat: implements number type inferencing

- crates/mun_codegen/src/test.rs
Fixes a cargo format that slipped through
> misc: run clang format

- crates/mun_abi/src/autogen_impl.rs
- crates/mun_runtime/src/assembly.rs
- crates/mun_runtime/tests/runtime.rs
Fixes a bug where in this example: 
```
pub fn fibonacci_n() -> i64 {
let n = arg();
fibonacci(n)
}
fn arg() -> i64 {
5
}
fn fibonacci(n: i64) -> i64 {
if n <= 1 {
n
} else {
fibonacci(n - 1) + fibonacci(n - 2)
}
}
```
the `Runtime` complained that `arg` could not be found. However, this was already linked at build time by the compiler.
> fix: prevent runtime from linking internal symbols

- crates/mun_runtime/tests/memory.rs
Adds a test to make sure type conversion works when memory mapping.
> test(memory): add type conversion test

- crates/mun_abi/src/autogen_impl.rs
- crates/mun_runtime/src/assembly.rs
- crates/mun_runtime/tests/marshalling.rs
- crates/mun_runtime_capi/src/lib.rs
- crates/mun_runtime_capi/src/tests.rs
Enables adding extern functions to the runtime through the C api
Uses: https://github.com/mun-lang/runtime-ffi/pull/7
> misc: enables adding extern functions through c api

- crates/mun_runtime/examples/buoyancy.rs
- crates/mun_runtime/examples/fibonacci.rs
- crates/mun_runtime/examples/resources/buoyancy.mun
- crates/mun_runtime/examples/resources/fibonacci.mun
Adds an example that showcases a Mun app state setup, struct hot reloading, and struct marshalling.
> misc(runtime): add buoyancy example

- Cargo.toml
- README.md
Adds the use of rpath so our c binaries dont contain a full path.
> fix: adds the use of rpath so our c binaries dont contain a full path

- book/.gitignore
- book/ci/build
- netlify.toml
This fix adds a base url for branch deployments of the book. If all goes well it should add the tag:
```html
<base href=http://docs.mun-lang.org/v0.2" />
```
for the release branch.
> fix: base url added to book

- book/listings/ch01-getting-started/listing01.mun
Hi there, I was reading through the Mun book, and noticed that this example doesn't compile as written in the book.
> fix: remove return-blocking semicolon from ch01 listing 01

- book/src/ch02-02-functions.md
Markdown doesn't close code-blocks when the closing ```` ``` ```` isn't on a separate line.
[Rendering the change](https://github.com/mun-lang/mun/pull/194/files?short_path=6df04f5#diff-6df04f553edc809e85cc5b754ca0211b) shows the difference and it also happens [in the rendered book](https://docs.mun-lang.org/v0.2/ch02-02-functions.html#function-access-modifier).
> Fix code blocks in ch02-02-functions of the book

- book/book.toml
- book/ci/build
- book/theme/trailing_slash_hack.js
- netlify.toml
This PR replaces the overly complex logic to make the documentation for v0.2 available under a subdirectory. 
Instead of adding a `base` tag to the documentation this PR adds some simple javascript to add a trailing slash to a url if the url doesnt end in `.html`. That should fix our relative path issues.
It also removes the need for mdbook v0.4 so I reverted back to just downloading the binary. That should make our CI mucho faster.
As an added bonus I also added a github icon that links back this repo.
We also have to push these changes to `release/v0.2`.
Closes https://github.com/mun-lang/mun/issues/195
Closes https://github.com/mun-lang/mun/issues/190
> fix: replaced overly complicated redirection rules with a simple hack

- book/listings/ch01-getting-started/listing04.rs
> Fix missing arg for fibonacci fn

- .github/actions/install-llvm/dist/index.js
- .github/actions/install-llvm/index.js
- .github/actions/install-llvm/package-lock.json
- .github/workflows/ci.yml
This fixes the windows builds. It was broken because GitHub added msys64 to their windows environments which include a copy of libclang. Using that however, resulted in an error. 
This PR adds the LIBCLANG_PATH environment variable when installing LLVM on windows. That way it uses libclang from the version of LLVM we install anyway.
> misc: fix windows libclang issues

- crates/mun/Cargo.toml
- crates/mun/src/main.rs
- crates/mun_language_server/Cargo.toml
- crates/mun_language_server/src/capabilities.rs
- crates/mun_language_server/src/lib.rs
- crates/mun_language_server/src/main_loop.rs
- crates/mun_language_server/src/protocol.rs
- crates/mun_language_server/src/protocol/connection.rs
- crates/mun_language_server/src/protocol/error.rs
- crates/mun_language_server/src/protocol/message.rs
- crates/mun_language_server/src/protocol/stdio.rs
- crates/mun_language_server/tests/initialization.rs
- crates/mun_language_server/tests/support.rs
This is the initial language server implementation. The `mun` executable learned a new subcommand: `language-server`. When running this command it will act as a language server that communicates over stdin and stdout according to the [language server protocol](https://microsoft.github.io/language-server-protocol/). This is used by our [vscode-extension](https://github.com/mun-lang/vscode-extension) to provide language integration. However, the idea behind the language server protocol is to be able to be integrated with multiple IDE's.
Although I very much looked at rust-analyzer for this, this implementation is fully async as I felt that was the more rusty way to do it.
This PR just adds the very bare bones. No actual features are implemented for the sake of keeping PRs small I say we …
> feat: language server setup

- crates/mun_codegen/src/ir/dispatch_table.rs
- crates/mun_codegen/src/snapshots/test__nested_private_extern_fn.snap
- crates/mun_codegen/src/snapshots/test__nested_private_fn.snap
- crates/mun_codegen/src/snapshots/test__nested_private_recursive_fn.snap
- crates/mun_codegen/src/snapshots/test__nested_private_recursive_fn_with_args.snap
- crates/mun_codegen/src/test.rs
This is a fix for the Mun v0.2 release, which should also be cherry-picked/pushed to the `release/v0.2` branch and released as v0.2.1 (at some point).
We've also discussed a more elaborate solution where we first do a pass to determine all "used" functions. I'll leave that for future work, as this patch should be rolled out
> fix(codegen): crash on missing nested private function

- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/test__issue_228.snap
- crates/mun_codegen/src/snapshots/test__issue_228_never_if.snap
- crates/mun_codegen/src/test.rs
Fixes a few issues (presented in https://github.com/mun-lang/mun/issues/228):
* In IR: When a block had a tailing expression with a `never` type the block would return an empty struct.
* If the `then` block of an `if`/`else` expression had a never type, it would return an empty struct instead of the result of the `if` statement.
* If the `then` block and the `else` block have a never type, the if would return an empty struct.
> fix: fixes issue #228

- crates/mun_runtime/src/lib.rs
Fixes clippy warnings in macro. 
https://rust-lang.github.io/rust-clippy/master/#many_single_char_names
> fix: clippy::many_single_char_names in macro

- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/mun_codegen__test__field_crash.snap
- crates/mun_codegen/src/snapshots/mun_codegen__test__field_expr.snap
- crates/mun_codegen/src/snapshots/mun_codegen__test__gc_struct.snap
- crates/mun_codegen/src/snapshots/mun_codegen__test__issue_225.snap
- crates/mun_codegen/src/snapshots/mun_codegen__test__struct_test.snap
- crates/mun_codegen/src/snapshots/test__issue_225.snap
- crates/mun_codegen/src/test.rs
Fixes an issue where taking the field of a temporary crashed the compiler. This was caused by a field expression always expecting a "place" expression which is actually not always the case (in the case of a temporary for example).
Closes #225
> fix: fixes issues #225

- crates/mun_codegen_macros/src/lib.rs
Fixes an issue with tarpaulin with skipping some procedural macro code.
See: https://github.com/xd009642/tarpaulin#ignoring-code-in-files
> fix: proper tarpaulin skip attribute

- crates/mun/src/lib.rs
These comments are misleading as the functions do not return `bool`s
> fix: removed outdated comments

- book/listings/ch01-getting-started/listing04.rs
- book/listings/ch02-basic-concepts/listing02.rs
- book/listings/ch02-basic-concepts/listing03.rs
- book/listings/ch03-structs/listing11.rs
- book/listings/ch03-structs/listing12.rs
- book/listings/ch03-structs/listing14.rs
- crates/mun/src/ops/start.rs
- crates/mun/tests/integration.rs
- crates/mun_abi/Cargo.toml
- crates/mun_hir/Cargo.toml
- crates/mun_memory/Cargo.toml
- crates/mun_runtime/Cargo.toml
- crates/mun_runtime/benches/benchmarks.rs
- crates/mun_runtime/benches/resources/empty.mun
- crates/mun_runtime/benches/resources/fibonacci.mun
- crates/mun_runtime/benches/resources/struct.mun
- crates/mun_runtime/examples/buoyancy.rs
- crates/mun_runtime/examples/fibonacci.rs
- crates/mun_runtime/src/adt.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/src/macros.rs
- crates/mun_runtime/src/marshal.rs
- crates/mun_runtime/src/reflection.rs
- crates/mun_runtime/src/struct_ref.rs
- crates/mun_runtime/tests/hot_reloading.rs
- crates/mun_runtime/tests/marshalling.rs
- crates/mun_runtime/tests/memory.rs
- crates/mun_runtime/tests/util.rs
This PR resolves issue #224, while introducing several benchmarks for tracking marshalling performance. There are two new benchmarks:
- retrieving data from a struct field
- writing data to a struct field
Both benchmarks are tested for:
- Rust fundamental type (`f32`)
- Mun fundamental type (`f32`)
- Rust shared reference to `struct`
- Rust clone of `struct`
- Mun garbage collected `struct`
- Mun value `struct`
Based on profiling two optimisations were made:
1. cache hashed values for constants (in the future these should use `const fn`s)
2. Store `StructRef` with a shared reference to the `Runtime` instead of a `Rc<RefCell<Runtime>>`
Especially the second optimisation is more involved, but results in the biggest performance gains:
_Optimisation 2_ has the added side-effect that …
> improvement(runtime): add benchmarks for and optimise struct field marshalling

- crates/mun_codegen/src/code_gen.rs
- crates/mun_codegen/src/code_gen/bitcode_file.rs
- crates/mun_codegen/src/code_gen/error.rs
- crates/mun_codegen/src/code_gen/module_builder.rs
Instead of emitting object files the compiler emits LLVM bitcode files. This enables LLD to understand the whole program which enables future further optimizations like LTO.
> refactor(codegen): emit and link bitcode files instead of object files

- crates/mun_codegen/src/code_gen.rs
- crates/mun_codegen/src/code_gen/error.rs
- crates/mun_codegen/src/code_gen/module_builder.rs
- crates/mun_codegen/src/code_gen/object_file.rs
This reverts commit 073623952312f300ccefebc018e2bed208b2074d or MR #258 . It doesnt work when generating MacOS binaries (build actually failed..). 
For MacOS we would have to generate object files so we would have two code paths. Id rather then just use object files for all platforms.
> fix: emit and link bitcode files instead of obj does not work on MacOS

- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/snapshots/mun_codegen__test__issue_262.snap
- crates/mun_codegen/src/test.rs
Solves an issue where if an initializer of a let statement has the never type it crashed the code generation. 
Fixes #262
> fix: never return type in let initializer

- crates/mun_codegen/src/ir/body.rs
- crates/mun_hir/src/adt.rs
- crates/mun_hir/src/arena.rs
- crates/mun_hir/src/arena/map.rs
- crates/mun_hir/src/code_model.rs
- crates/mun_hir/src/expr.rs
- crates/mun_hir/src/expr/scope.rs
- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/raw.rs
- crates/mun_hir/src/resolve.rs
- crates/mun_hir/src/source_id.rs
- crates/mun_hir/src/ty/infer.rs
- crates/mun_hir/src/ty/lower.rs
- crates/mun_hir/src/type_ref.rs
This PR refactors the Arena Id's a little bit so that we need fewer macros and get a clearer coupling between Arenas, their data and their ids. Similar to how rust analyzer refactored this. 
I also renamed a few Ids to indicate that they are "Local" to their container (`TypeRefId` is local to a specific `TypeRefMap` and is now called `LocalTypRefId`). I found that to be clearer.
> refactor: use Idx<T> instead of macro in arena

- crates/mun_hir/src/name.rs
- crates/mun_syntax/Cargo.toml
This PR bumps the version of smol_str.
`new_inline_from_ascii` has been deprecated by the following commit.
https://github.com/rust-analyzer/smol_str/commit/c30083d7779f4a6c95d1f3a2af239feaad9d9e31
> improvement: bump smol_str dependency to 0.1.17

- crates/mun_hir/src/adt.rs
- crates/mun_hir/src/code_model.rs
- crates/mun_hir/src/code_model/src.rs
- crates/mun_hir/src/db.rs
- crates/mun_hir/src/expr/validator/tests.rs
- crates/mun_hir/src/ids.rs
- crates/mun_hir/src/item_tree.rs
- crates/mun_hir/src/item_tree/lower.rs
- crates/mun_hir/src/item_tree/snapshots/mun_hir__item_tree__tests__top_level_items.snap
- crates/mun_hir/src/item_tree/tests.rs
- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/source_id.rs
- crates/mun_hir/src/ty/tests.rs
First refactor to remove RawItems and create better separation of concerns. ItemTree is a derived AST that only contains module items. All interning is now done as ItemTree ids instead of building directly on the AST. Hopefully, this creates a clearer separation between items and the AST.
When adding modules (which Im also working on) having this ItemTree is much clearer than using either RawItems or the code model or a strange combination. Im not sure yet how to handle the `TypeRefSourceMap`, Im looking into removing that too.
> feature: refactored RawItems into ItemTree

- crates/mun_hir/Cargo.toml
- crates/mun_hir/src/expr/validator/tests.rs
- crates/mun_hir/src/fixture.rs
- crates/mun_hir/src/item_tree/tests.rs
- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/mock.rs
- crates/mun_hir/src/tests.rs
- crates/mun_hir/src/ty/tests.rs
- crates/mun_test/Cargo.toml
- crates/mun_test/src/fixture.rs
- crates/mun_test/src/lib.rs
Adds the ability to construct test fixtures that consist of multiple files from a single string. A fixture with multiple files looks like this:
```rust
Fixture::parse(
r#"
//- /foo.mun
fn hello_world() {
}
//- /bar.mun
fn baz() {
}
"#
)
```
This is used by the MockDatabase to enable creating tests for multiple files.
> feature: adds fixtures to support multiple files from string

- book/book.toml
- book/listings/ch01-getting-started/listing01.mun
- book/listings/ch01-getting-started/listing02.mun
- book/src/ch01-02-hello-fibonacci.md
- book/src/ch01-03-hello-hot-reloading.md
- book/src/ch02-01-values-and-types.md
- book/src/ch02-02-functions.md
- book/src/ch02-03-control-flow.md
- book/src/ch02-04-extern-fn.md
- book/src/ch03-04-hot-reloading-structs.md
- crates/mun_mdbook_test_plugin/Cargo.toml
- crates/mun_mdbook_test_plugin/src/main.rs
This pull request add mdbook plugin that's test all mun code(indicated by keyword `mun` before code block).
Also, plugin allows to specify "testing method" for each code block by using keywords `no_run`, `compile_fail` and `skip`.
Example: `mun,no_run`, `mun,compile_fail` and etc
With this pull request, plugin already setted as dependency for mun book, so before building new version of book by `mdbook build` one need to compile `mdbook-mun-examples-test` crate and add it's executable file to environment variables.
closes #209
> feat: add mdbook plugin for testing mun code in book

- book/book.toml
- book/ci/build
This fixes an issue with Netlify not being able to build to book due to it not being able to find the test plugin. This PR comments out the test plugin when running in CI. Since we run the mdbook tests in the CI on Gitlab this is fine.
> fix: dont run mun tests on CI

- crates/mun_codegen/Cargo.toml
- crates/mun_codegen/src/ir/types.rs
- crates/mun_codegen/src/mock.rs
- crates/mun_codegen/src/value/array_value.rs
- crates/mun_codegen/src/value/float_value.rs
- crates/mun_codegen/src/value/int_value.rs
- crates/mun_codegen/src/value/mod.rs
- crates/mun_codegen/src/value/pointer_value.rs
- crates/mun_codegen/src/value/string.rs
- crates/mun_codegen_macros/Cargo.toml
- crates/mun_codegen_macros/src/lib.rs
> feat(codegen): add AsValue macro support for enums

- .github/workflows/release.yml
This should fix the release stage. The `set-env` command [has been deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) in favor of Environment Files. This PR changes this behavior to use that.
> fix: shorten commit hash with environment file

- crates/mun/Cargo.toml
- crates/mun/src/lib.rs
- crates/mun/src/ops/build.rs
- crates/mun/src/ops/init.rs
- crates/mun/src/ops/new.rs
- crates/mun/tests/integration.rs
- crates/mun_codegen/src/assembly.rs
- crates/mun_codegen/src/code_gen.rs
- crates/mun_codegen/src/code_gen/module_builder.rs
- crates/mun_codegen/src/code_gen/object_file.rs
- crates/mun_codegen/src/db.rs
- crates/mun_codegen/src/lib.rs
- crates/mun_codegen/src/test.rs
- crates/mun_compiler/Cargo.toml
- crates/mun_compiler/src/db.rs
- crates/mun_compiler/src/diagnostics_snippets.rs
- crates/mun_compiler/src/driver.rs
- crates/mun_compiler/src/driver/config.rs
- crates/mun_compiler/src/lib.rs
Adds the `--emit-ir` CLI flag to the `build` subcommand, for outputting LLVM IR to `*.ll` files instead of generating Mun libraries.
This PR also removes the need for `#[serial]` tests by adding and using a `path` input argument for the `init` and `new` subcommands, for deterministic execution of tests - in parallel.
> feat(cli): add option to emit IR

- .github/actions/install-llvm/dist/index.js
- .github/actions/install-llvm/index.js
While building this PR the windows action failed again while un7ziping due to with the file being unzipped still being in use by another process. I assume this is the extraction? I updated the code to retry 5 times and wait 1 second in between.
This PR calls 7z directly instead of relying in toolcache. This then outputs a lot of information about the 7zip process which is what we are currently still missing. The output of the install LLVM step now looks like this:
```
7-Zip (r) 19.00 (x64) : Igor Pavlov : Public domain : 2019-02-21
Scanning the drive for archives:
0M Scan D:\a\_temp\
1 file, 223656577 bytes (214 MiB)
Extracting archive: D:\a\_temp\e864a1e0-bd33-4774-9c01-4e4a8234f038
--
Path = D:\a\_temp\e864a1e0-bd33-4774-9c01-4e4a8234f038
Type = 7z
Physical Size = 223656577
Headers Size …
```
> fix: manually extract llvm release to get more output

- README.md
- book/src/SUMMARY.md
- book/src/ch04-02-building-llvm.md
Adds a guide on how to get LLVM and refers to that guide from the readme.
Note that I wrote this document differently from our other files. I put every sentence on a new line. This is something I use at my day job and makes reviewing a lot easier. I can change it back later but I don't think it really matters since the rendered version will look the same.
Closes #259
> feat(book): describe how to install/build LLVM

- crates/mun_syntax/src/parsing/event.rs
I found a loop that iterates over a lot of elements that accidentally loops O(n) times where it should be O(n). This caused huge performance issues that this MR fixes. 
The change looks more complicated than it actually is. What was happening was this:
```rust
for _i in 0..events.len() {
for i in 0..events.len() {
// Stuff
}
}
```
where it should be:
```rust
for i in 0..events.len() {
// Stuff
}
```
This caused completions in a large file that I'm using to go from 300ms to 3ms but it affected all operations.
> fix: parser performance issues

- README.md
- netlify.toml
Updates the netlify configuration to support a release v0.3. Also updates the readme to refer to v0.3 instead of v0.2.
> feature: add redirect target for v0.3 and update readme

- crates/mun_runtime/src/adt.rs
Derive `Clone` for `RootedStruct`. All types contained in the `RootedStruct` already properly support rooting so this was trivial. 
The `Clone::clone` function for a `RootedStruct` clones the references to the struct instead of the contents of the struct. Is that desirable? I think so because to me it would make more sense to have to clone the struct itself in Mun and return a new rooted struct.
> feat: derive clone for RootedStruct

- .github/workflows/ci.yml
Adds the use of https://github.com/Swatinem/rust-cache to enable caching of builds.
> misc(ci): cache cargo builds

- crates/mun_hir/src/expr/validator.rs
Removes a `dbg!` statement that was left over.
> fix: remove remaining dbg statement

- crates/mun_hir/src/code_model.rs
- crates/mun_hir/src/code_model/struct.rs
- crates/mun_hir/src/code_model/struct/validator.rs
- crates/mun_hir/src/code_model/struct/validator/snapshots/mun_hir__code_model__r#struct__validator__tests__private_leak_struct_fields.snap
- crates/mun_hir/src/code_model/struct/validator/tests.rs
- crates/mun_hir/src/expr/validator/tests.rs
- crates/mun_hir/src/utils.rs
Also exposed struct field visibility in the HIR and created a struct validation module
> Feat: Added private type leak validation to structs

- CONTRIBUTING.md
- crates/mun_hir/src/source_id.rs
Hi 👋 Fixes:
* `master` → `main`
* bread-first search → bradth-first search
Someone on Discord gave us this picture ha ha
> fix: minor typo

- crates/mun_codegen/Cargo.toml
- crates/mun_codegen/src/apple.rs
- crates/mun_codegen/src/lib.rs
- crates/mun_codegen/src/linker.rs
- crates/mun_target/src/spec/apple_base.rs
Apparently, since macOS Big Sur the location of system libraries moved. We now need to explicitly specify where to find these. I used the same technique used by Rust to locate this path. 
Closes #361
> fix: locate sdkroot required since big sur

- crates/mun_syntax/src/parsing/grammar.rs
Small fix: replaced  a `{` by `}` when parsing an `error_block`.
Example demonstrating wrong behavior:
```rs
{ /* error_block */ }
fn main() {}
```
Original output:
```
error: syntax error
--> mod.mun:1:1
|
1 | { /* error_block */ }
| ^ expected a declaration
|error: syntax error
--> mod.mun:1:21
|
1 | { /* error_block */ }
|                     ^ unmatched }
|
```
Output after fix (here, the `}` is parsed as part of the error_block):
```
error: syntax error
--> mod.mun:1:1
|
1 | { /* error_block */ }
| ^ expected a declaration
|
```
Does this need a test case? I'm not really sure what would be the best example for this (nor how this test case would be named).
> fix(parser): parse closing brace of error_block

- crates/mun_syntax/src/parsing/grammar/declarations.rs
Example of a problem this fixes:
```rs
use;
pub fn main() {}
```
Original output:
```
error: syntax error
--> mod.mun:1:4
|
1 | use;
|    ^ expected one of `self`, `super`, `package` or an identifier
|error: syntax error
--> mod.mun:1:5
|
1 | use;
|     ^ expected SEMI
|
```
Output after fix:
```
error: syntax error
--> mod.mun:1:4
|
1 | use;
|    ^ expected one of `self`, `super`, `package` or an identifier
|
```
> fix(parser): add semicolon to declaration recovery set

- .github/actions/install-llvm/dist/index.js
- .github/actions/install-llvm/index.js
- book/src/ch04-02-building-llvm.md
- crates/mun_codegen/Cargo.toml
- crates/mun_codegen/src/code_gen/symbols.rs
- crates/mun_codegen/src/intrinsics/macros.rs
- crates/mun_codegen/src/ir.rs
- crates/mun_codegen/src/ir/body.rs
- crates/mun_codegen/src/ir/dispatch_table.rs
- crates/mun_codegen/src/ir/ty.rs
- crates/mun_codegen/src/snapshots/mun_codegen__test__fibonacci.snap
- crates/mun_codegen/src/snapshots/mun_codegen__test__loop_break_expr.snap
- crates/mun_codegen/src/value/function_value.rs
- crates/mun_lld/Cargo.toml
- scripts/install-llvm.sh
Updates LLVM to 12.0.1. As LLVM 11.0.1 has been pulled from `apt` in favour of 11.1.0, we need to upgrade.
This will also unblock the release of Mun 0.3.1 - containing bug fixes.
> misc: upgrade to LLVM 12.0.1

- book/listings/ch01-getting-started/listing04.rs
- book/listings/ch02-basic-concepts/listing02.rs
- book/listings/ch02-basic-concepts/listing03.rs
- book/listings/ch03-structs/listing11.rs
- book/listings/ch03-structs/listing12.rs
- book/listings/ch03-structs/listing14.rs
- crates/mun/src/ops/start.rs
- crates/mun/tests/integration.rs
- crates/mun_memory/src/gc/root_ptr.rs
- crates/mun_runtime/benches/benchmarks.rs
- crates/mun_runtime/benches/util/mod.rs
- crates/mun_runtime/examples/buoyancy.rs
- crates/mun_runtime/examples/fibonacci.rs
- crates/mun_runtime/src/adt.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/tests/hot_reloading.rs
- crates/mun_runtime/tests/marshalling.rs
- crates/mun_runtime/tests/memory.rs
- crates/mun_runtime/tests/runtime.rs
- crates/mun_runtime/tests/threading.rs
- crates/mun_runtime/tests/util.rs
- crates/mun_skeptic/src/runtime.rs
- crates/mun_test/src/driver.rs
Removes the need to put the `Runtime` into a `Rc<RefCell<Runtime>>`. This makes the `Runtime` `Send`.
Closes  #299
> feat: make the runtime send

- crates/mun_runtime/Cargo.toml
- crates/mun_runtime/benches/benchmarks.rs
- crates/mun_runtime/benches/util/mod.rs
> fix: wasmer-runtime deprecation

- .gitmodules
- c/LICENSE-APACHE
- c/LICENSE-MIT
- c/README.md
- c/include/mun/abi.h
- crates/tools/src/abi.rs
Removes the `abi` ffi submodule and places the generated ABI header in the repository itself.
> refactor: remove abi submodule

- .github/workflows/release.yml
- README.md
- book/book.toml
- book/ci/build
- book/netlify.toml
This is an attempt to move the book netlify stuff to the book folder so we can remove our custom ignore and let netlify handle that properly.
> fix: move netlify to custom folder

- CHANGELOG.md
This PR adds a Changelog following https://keepachangelog.com/en/1.0.0/
From now on, when you create an MR you can choose to add a changelog entry. Only the entries in the changelog will be included in the final release notes. This allows you to be a bit more elaborate in your changelog.
> feat: adds a changelog

- .cargo/config
- .github/workflows/ci.yml
- CHANGELOG.md
- crates/mun_codegen/src/test.rs
Use llvm-cov instead of tarpauling to compute coverage. LLVM-cov uses recently stabilized code coverage metrics emitted by the rust compiler. This also then works on Windows and MacOS and can be collected while running the regular tests.
I did have to change some tests to no longer use the name of the thread that is executing the tests. This is because that behavior (which was unstable in the first place) doesn't work with llvm-cov.
> feat: use llvm-cov for coverage

- .github/workflows/release.yml
Tested in a temporary `release/*` branch: https://github.com/mun-lang/mun/actions/runs/3826916629
> improvement: remove commit hash from release artifacts

- crates/mun_libloader/Cargo.toml
- crates/mun_libloader/src/lib.rs
- crates/mun_libloader/src/temp_library.rs
- crates/mun_memory/src/lib.rs
- crates/mun_memory/src/type/mod.rs
- crates/mun_runtime/Cargo.toml
- crates/mun_runtime/src/assembly.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/tests/runtime.rs
- crates/mun_test/src/driver.rs
> improvement: convert anyhow to thiserror errors

- crates/mun_memory/src/mapping.rs
- crates/mun_runtime/tests/hot_reloading.rs
- crates/mun_runtime/tests/memory.rs
- crates/mun_test/src/driver.rs
> test: add multi-file hot reloading test

- crates/mun_runtime/src/dispatch_table.rs
- crates/mun_runtime/src/lib.rs
- crates/mun_runtime/src/utils.rs
- crates/mun_runtime/tests/functions.rs
If a function is not found, a suggestion is added to the error message if a close match exists. 
To measure if there is a close match, the difference between the names are measured using Levenshtein distance, the approach is based on here: https://github.com/rust-lang/rust/blob/488acf86a75c56d30b16822e953c505a9e4901a7/compiler/rustc_span/src/lev_distance.rs#L46-L48
Fixes: #412
> feat: provide suggestions if a function cannot be found

- crates/mun_abi/src/primitive.rs
- crates/mun_codegen/src/value/mod.rs
- crates/mun_compiler/src/lib.rs
- crates/mun_diagnostics/src/hir.rs
- crates/mun_diagnostics/src/lib.rs
- crates/mun_syntax/src/parsing/event.rs
- crates/mun_target/src/abi/align.rs
- crates/mun_target/src/abi/integer.rs
- crates/mun_target/src/abi/mod.rs
- crates/mun_target/src/abi/size.rs
- crates/mun_vfs/src/monitor.rs
> docs: fix incorrect inner doc comments

- crates/mun_runtime_capi/src/function.rs
As no strong reference was active anymore, the OS could free the memory, overwriting the original strong count value. Now, we're ensuring that at least one strong reference exists at the end of the test, to avoid memory from being freed
> fix: test_function_release_strong_count

- crates/mun_hir/src/item_tree.rs
- crates/mun_hir/src/item_tree/lower.rs
- crates/mun_hir/src/item_tree/pretty.rs
- crates/mun_hir/src/item_tree/snapshots/mun_hir__item_tree__tests__top_level_items.snap
- crates/mun_hir/src/item_tree/tests.rs
- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/package_defs/collector.rs
- crates/mun_hir/src/pretty.rs
A refactor to format `ItemTree`s properly. I need this for testing `impl`s.
> refactor: improve item tree display

- crates/mun_runtime/src/lib.rs
Replaces it with a raw pointer. Avoids possible Undefined Behavior.
Stripped-down example of how the current code fails in Miri: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4b7ad1c81275f9213a60443a7edafc4f)
Equivalent using the implementation from this PR: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8e64a9b45aa78b8823f5453b9c54d3a5)
> fix: don't perform invalid reference cast

- .github/workflows/ci.yml
- crates/mun_compiler/src/diagnostics.rs
- crates/mun_hir/src/code_model/function.rs
- crates/mun_hir/src/item_tree.rs
- crates/mun_hir/src/item_tree/lower.rs
- crates/mun_hir/src/item_tree/pretty.rs
- crates/mun_hir/src/source_id.rs
- crates/mun_language_server/Cargo.toml
- crates/tools/src/lib.rs
Adds the `Param` type to `Function` which gives access to the source of the parameter.
I also fixed a few deprecation warnings.
> feat: add Param type to Function

- crates/mun_hir/src/code_model.rs
- crates/mun_hir/src/code_model/function.rs
- crates/mun_hir/src/db.rs
- crates/mun_hir/src/display.rs
- crates/mun_hir/src/method_resolution.rs
- crates/mun_hir/src/name.rs
- crates/mun_hir/src/path.rs
- crates/mun_hir/src/visibility.rs
Adds methods to perform method resolution for `impl` blocks. Also implements `hir::Display` for a number of types because they are used in snapshot tests.
> feat: method resolution

- Cargo.toml
- crates/mun/Cargo.toml
- crates/mun_abi/Cargo.toml
- crates/mun_capi_utils/Cargo.toml
- crates/mun_codegen/Cargo.toml
- crates/mun_codegen_macros/Cargo.toml
- crates/mun_compiler/Cargo.toml
- crates/mun_compiler_daemon/Cargo.toml
- crates/mun_diagnostics/Cargo.toml
- crates/mun_diagnostics/src/hir/duplicate_definition_error.rs
- crates/mun_hir/Cargo.toml
- crates/mun_hir/src/line_index.rs
- crates/mun_language_server/Cargo.toml
- crates/mun_libloader/Cargo.toml
- crates/mun_memory/Cargo.toml
- crates/mun_paths/Cargo.toml
- crates/mun_project/Cargo.toml
- crates/mun_runtime/Cargo.toml
- crates/mun_runtime_capi/Cargo.toml
- crates/mun_skeptic/Cargo.toml
- crates/mun_syntax/Cargo.toml
- crates/mun_target/Cargo.toml
- crates/mun_test/Cargo.toml
- crates/mun_vfs/Cargo.toml
- crates/tools/Cargo.toml
Move all dependencies to workspace dependencies to ensure we have no duplicates. I only left two versions of `notify` because it would be a relatively big refactor. 
I used https://github.com/mainmatter/cargo-autoinherit to automate most of this.
> refactor: move to workspace dependencies

- crates/mun_hir/src/method_resolution.rs
- crates/mun_hir/src/ty/infer.rs
- crates/mun_hir/src/ty/snapshots/mun_hir__ty__tests__infer_access_hidden_assoc_function.snap
- crates/mun_hir/src/ty/snapshots/mun_hir__ty__tests__infer_assoc_function.snap
- crates/mun_hir/src/ty/tests.rs
Adds the ability to infer the type of associate function calls.
> feat: infer associate functions

- crates/mun_hir/src/lib.rs
- crates/mun_hir/src/semantics.rs
- crates/mun_hir/src/semantics/source_to_def.rs
- crates/mun_hir/src/source_analyzer.rs
- crates/mun_hir/src/ty.rs
- crates/mun_language_server/src/completion/dot.rs
- crates/mun_language_server/src/completion/expr.rs
- crates/mun_language_server/src/completion/snapshots/mun_language_server__completion__dot__tests__param.snap
- crates/mun_language_server/src/completion/snapshots/mun_language_server__completion__dot__tests__self.snap
- crates/mun_language_server/src/completion/snapshots/mun_language_server__completion__expr__tests__associated_self.snap
- crates/mun_language_server/src/completion/snapshots/mun_language_server__completion__expr__tests__complete_self.snap
- crates/mun_language_server/src/completion/snapshots/mun_language_server__completion__expr__tests__parameter.snap
Builds on #578 
Adds completion for `self` and `Self` in `impl` blocks.
> feat: completion of `self` and `Self`
