mun-lang/mun

crates/mun_compiler/src/lib.rs, crates/mun_hir/src/code_model.rs, crates/mun_hir/src/diagnostics.rs, crates/mun_syntax/src/ast/extensions.rs
The thing that is still missing in the PR is a test to actually check that this works but currently there is no testing framework to test HIR in the first place.
=> feat: adds detection of duplicate definition names

crates/mun_abi/src/autogen.rs
=> Unit tests for auto-generated ABI structs

crates/mun_abi/src/autogen.rs, crates/mun_codegen/src/code_gen.rs, crates/mun_codegen/src/code_gen/symbols.rs, crates/mun_codegen/src/ir/dispatch_table.rs, crates/mun_codegen/src/ir/function.rs, crates/mun_codegen/src/ir/module.rs, crates/mun_codegen/src/ir/ty.rs, crates/mun_codegen/src/lib.rs, crates/mun_compiler/src/lib.rs, crates/mun_hir/src/ty/infer.rs, crates/mun_runtime/src/assembly.rs, crates/mun_runtime/src/lib.rs
=> Solve clippy warnings

ci/azure-coverage.yml
See also xd009642/tarpaulin#264. Should probably revert this once tarpaulin is fixed.
=> fix(ci): Use --test-threads=1 to prevent a segfault

crates/mun_abi/src/macros.rs
Now it matches the perspective of a Mun developer
=> improvement(abi): swap expected and found types

crates/tools/src/lib.rs
Fixes issues with grammar test on windows.
=> fix: grammar is fresh test on windows

crates/mun/Cargo.toml, crates/mun_abi/Cargo.toml, crates/mun_codegen/Cargo.toml, crates/mun_compiler/Cargo.toml, crates/mun_compiler_daemon/Cargo.toml, crates/mun_errors/Cargo.toml, crates/mun_hir/Cargo.toml, crates/mun_lld/Cargo.toml, crates/mun_runtime/Cargo.toml, crates/mun_runtime_capi/Cargo.toml, crates/mun_syntax/Cargo.toml, crates/mun_target/Cargo.toml, crates/tools/Cargo.toml
- Bumps version of all crates to v0.2.0
- Changes authors of all crates to _The Mun Team_
=> Bump crate version and change authors

crates/mun_compiler_daemon/src/lib.rs
=> fix(hotreloading): no more 'successfully compiled' message if code has errors

crates/mun_compiler/src/diagnostics/emit.rs
=> fix(diagnostic): move console cursor to new line after error log

crates/mun_codegen/src/ir/body.rs, crates/mun_codegen/src/snapshots/test__arithmetic_op_float.snap.new, crates/mun_codegen/src/snapshots/test__arithmetic_op_int.snap.new, crates/mun_codegen/src/snapshots/test__assignment_op_float.snap.new, crates/mun_codegen/src/snapshots/test__assignment_op_int.snap.new, crates/mun_codegen/src/snapshots/test__compare_op_bool.snap, crates/mun_codegen/src/snapshots/test__compare_op_float.snap.new, crates/mun_codegen/src/snapshots/test__compare_op_int.snap.new, crates/mun_codegen/src/test.rs, crates/mun_hir/src/ty/op.rs
Implements missing binary comparison operator
=> fix: implements binary comparison operator for bool

README.md
Removes unused badge definitions and uses shield.io for all badges where available.
=> misc: updated readme badges

README.md
Updates the readme with a working example.
=> misc: updated readme

crates/mun_lld/wrapper/lld-c.cpp
Adds a mutex around the LLD on macOS. Also added to WASM for the future.
=> fix: adds a mutex around the lld wrapper for macOS

crates/mun/Cargo.toml, crates/mun/src/main.rs, crates/mun_codegen/Cargo.toml, crates/mun_codegen/src/code_gen.rs, crates/mun_codegen/src/code_gen/linker.rs, crates/mun_compiler/Cargo.toml, crates/mun_compiler/src/driver.rs, crates/mun_compiler/src/lib.rs, crates/mun_compiler_daemon/Cargo.toml, crates/mun_compiler_daemon/src/lib.rs, crates/mun_runtime/Cargo.toml, crates/mun_runtime/src/assembly.rs, crates/mun_runtime/src/assembly/temp_library.rs, crates/mun_runtime/src/lib.rs, crates/mun_runtime/tests/util.rs, crates/mun_runtime_capi/Cargo.toml, crates/mun_runtime_capi/src/gc.rs, crates/mun_runtime_capi/src/hub.rs, crates/mun_runtime_capi/src/lib.rs, crates/mun_target/Cargo.toml, crates/mun_target/src/spec.rs, crates/tools/Cargo.toml, crates/tools/src/abi.rs, crates/tools/src/lib.rs, crates/tools/src/syntax.rs
BREAKING CHANGE: New concrete error type in public APIs
closes #177
Alternate to #180 
I have not addressed existing CI failures on master in this PR
=> refactor!: Replace deprecated failure crate with thiserror and anyhow

crates/mun_abi/src/lib.rs, crates/mun_codegen/src/code_gen/linker.rs, crates/mun_codegen/src/code_gen/symbols.rs, crates/mun_runtime/src/assembly.rs
=> improvement: added combatibility check between munlib and runtime

.github/actions/install-llvm/dist/index.js, .github/actions/install-llvm/index.js, .github/actions/install-llvm/package-lock.json, .github/actions/install-llvm/package.json, .github/workflows/ci.yml
Attempt to fix windows build errors with llvm. I couldn't get CI to fail with this PR (of course), so this just adds some logging to hopefully diagnose the problem in the future.
=> misc: adds logging to windows llvm install

README.md, book/ci/build-highlight-js, book/listings/ch01-getting-started/listing03.cpp, book/listings/ch02-basic-concepts/listing04.mun, book/listings/ch02-basic-concepts/listing05.mun, book/listings/ch02-basic-concepts/listing06.mun, book/src/SUMMARY.md, book/src/ch01-02-hello-fibonacci.md, book/src/ch01-03-hello-hot-reloading.md, book/src/ch02-01-values-and-types.md, book/src/ch02-02-functions.md, book/src/ch02-03-control-flow.md, book/src/ch02-04-extern-fn.md, book/src/ch02-05-use-keyword.md, book/src/ch03-00-structs.md, book/src/ch03-01-records-vs-tuples.md, book/src/ch03-02-struct-memory-kind.md, book/src/ch03-03-marshalling.md, book/src/ch03-04-hot-reloading-structs.md, book/src/ch04-00-developer-docs.md, book/src/ch04-01-salsa.md
=> feat(book): updated book for 0.3 changes

book/src/ch01-02-hello-fibonacci.md
=> fix: mdbook test failed

crates/mun/Cargo.toml, crates/mun_codegen/Cargo.toml, crates/mun_hir/Cargo.toml, crates/mun_language_server/Cargo.toml, crates/mun_memory/Cargo.toml, crates/mun_runtime/Cargo.toml, crates/mun_runtime_capi/Cargo.toml
Fixes some issues with cargo dev dependency versions which are required for publishing.
=> fix: cargo versions for publishing

book/src/SUMMARY.md, book/src/rfcs/0001-dynamically-sized-arrays.md, book/src/rfcs/rfcs.md
This is an RFC for dynamically sized arrays in Mun.
[Rendered](https://deploy-preview-324--docs-mun-lang.netlify.app/rfcs/0001-dynamically-sized-arrays.html)
=> [RFC] dynamically sized arrays

crates/mun_syntax/src/parsing/parser.rs
=> fix: fixed braces in parser error recovery

book/src/ch04-02-building-llvm.md
To avoid an issue with the Polly llvm library
=> docs: added a required ubuntu library to the book

crates/mun_vfs/Cargo.toml, crates/mun_vfs/src/monitor/notify_monitor.rs
Fixes a compiler error due to a breaking change in `notify`.
=> fix: notify watcher trait

crates/mun_hir/src/ty.rs, crates/mun_hir/src/ty/infer/type_variable.rs, crates/mun_hir/src/ty/snapshots/mun_hir__ty__tests__issue_354.snap, crates/mun_hir/src/ty/tests.rs
Fixes #354: types were not considered equal if they had already been resolved
=> fix: issue 354

.github/workflows/ci.yml, crates/mun_compiler/src/driver.rs
Fixes the benchmarks! 
Also added `cargo check --all-targets` to ensure the benchmarks are checked too.
=> fix: benchmark compilation and running

.github/actions/install-llvm/dist/index.js, .github/actions/install-llvm/index.js, .github/workflows/ci.yml, .github/workflows/release.yml
Builds Mun in CI with `-Ctarget-feature=+crt-static` 
Fixes: #322 
Depends on: #375
=> feat: use static-crt on windows

crates/mun_syntax/src/utils.rs
=> fix: rowan deprecation

crates/mun_abi/Cargo.toml, crates/mun_codegen/Cargo.toml, crates/mun_runtime/Cargo.toml, crates/mun_skeptic/Cargo.toml, crates/mun_target/Cargo.toml, crates/tools/Cargo.toml
Removes a whole bunch of dependencies to hopefully reduce compile times.
=> refactor: cleanup dependencies

.github/workflows/ci.yml, scripts/install-llvm.sh
=> fix: install llvm under ubuntu 22.04

crates/mun_codegen/Cargo.toml
=> bump: inkwell beta.5

.github/actions/install-llvm/dist/index.js, .github/actions/install-llvm/index.js, .github/workflows/ci.yml, .gitmodules, CHANGELOG.md, README.md, book/src/ch04-02-building-llvm.md, cpp/tests/CMakeLists.txt, cpp/tests/catch_main.cc, cpp/tests/extern.cc, cpp/tests/marshal.cc, cpp/tests/runtime.cc, crates/mun_codegen/Cargo.toml, crates/mun_codegen/src/ir/body.rs, crates/mun_codegen/src/snapshots/mun_codegen__test__conditional_return_expr.snap, crates/mun_codegen/src/snapshots/mun_codegen__test__issue_228.snap, crates/mun_codegen/src/snapshots/mun_codegen__test__loop_issue_llvm13.snap, crates/mun_codegen/src/snapshots/mun_codegen__test__never_conditional_return_expr.snap, crates/mun_codegen/src/test.rs, scripts/install-llvm.sh
Closes: https://github.com/mun-lang/mun/pull/368
=> bump: LLVM 13

.github/workflows/bump-pre-release.yml, .github/workflows/bump-release.yml, crates/mun/Cargo.toml, crates/mun_codegen/Cargo.toml, crates/mun_compiler/Cargo.toml, crates/mun_compiler_daemon/Cargo.toml, crates/mun_diagnostics/Cargo.toml, crates/mun_hir/Cargo.toml, crates/mun_language_server/Cargo.toml, crates/mun_libloader/Cargo.toml, crates/mun_memory/Cargo.toml, crates/mun_project/Cargo.toml, crates/mun_runtime/Cargo.toml, crates/mun_runtime_capi/Cargo.toml, crates/mun_skeptic/Cargo.toml, crates/mun_syntax/Cargo.toml, crates/mun_test/Cargo.toml, crates/mun_vfs/Cargo.toml
Adds a workflow that can be used to bump from a `.dev` release to a normal release. The workflow will create a PR with the changes.
=> feat: bump release workflow

CMakeLists.txt
This allows C++ projects to be built without requiring settings.
=> improvement: add default settings for CMake

crates/mun_hir/src/code_model/function.rs, crates/mun_hir/src/code_model/struct.rs, crates/mun_hir/src/code_model/type_alias.rs, crates/mun_hir/src/db.rs, crates/mun_hir/src/diagnostics.rs, crates/mun_hir/src/expr/validator.rs, crates/mun_hir/src/expr/validator/tests.rs, crates/mun_hir/src/ty.rs, crates/mun_hir/src/ty/infer.rs, crates/mun_hir/src/ty/infer/type_variable.rs, crates/mun_hir/src/ty/infer/unify.rs, crates/mun_hir/src/ty/lower.rs, crates/mun_hir/src/ty/tests.rs
Resolves https://github.com/mun-lang/mun/issues/339
Should be merged after https://github.com/mun-lang/mun/pull/527
=> refactor: detect cyclic type aliases and leaked privacy in validator

CONTRIBUTING.md, README.md, book/src/dev/02-building-llvm.md
fix: update llvm version to 14 in docs
minor typo in TDD acronym.
=> docs: update llvm version to 14
